name: IE Tests

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  local-tests:
    name: Local Tests
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.7, 3.1 ]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: |
          bundle exec rake spec:ie
        env:
          DISPLAY: :99
